"""Regenerate mocks/api_chat_response.json from what the agent actually replies.

P1's exporter seeds this file only if it is missing and never overwrites it, so
the fixture P4 falls back to is ours to keep honest. It matters because mock mode
is the backup-video path: a fixture that says "yes you can go" while the live
agent says "not yet" would put two different answers on stage depending on which
mode the laptop was in.

    python -m seed.export_chat_fixture

Run it after anything that changes the reply — a retuned dataset, a new engine
reason, a change to the router.
"""

from __future__ import annotations

import json

from backend.agent import loop
from backend.nessie import config, db

#: The §9 demo question, in Ana's language.
QUESTION = "¿Puedo permitirme ir a Chicago este finde? Unos 250$"
USER = "ana"


def build(conn=None) -> dict:
    own = conn is None
    conn = conn or db.connect()
    try:
        reply = loop.answer(conn, USER, QUESTION)
    finally:
        if own:
            conn.close()

    out = {
        "_owner": "P3 — generated by `python -m seed.export_chat_fixture`, not hand-written",
        "_question": QUESTION,
        "_note": "The real reply from the agent. Regenerate whenever the numbers move.",
        **{k: v for k, v in reply.items() if not k.startswith("_")},
    }
    # The proposed action's id is random per run; a fixture wants a stable one.
    if out.get("proposed_action"):
        out["proposed_action"] = {**out["proposed_action"], "id": "act_demo_transfer"}
    return out


def main() -> int:
    path = config.MOCKS_DIR / "api_chat_response.json"
    payload = build()
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(config.ROOT)}")
    print(f"  mode   : {loop.status()['mode']}")
    print(f"  reply  : {payload['reply'][:100]}")
    action = payload.get("proposed_action")
    print(f"  action : {action['label'] if action else 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
